POST http://localhost:3004/api/smoke-products
Content-Type: application/json

{
  "name": "Dip Devices Evri 510 Pod Attachment",
  "brand": "Dip Devices",
  "categories": "Vaporizer",
  "price": 7600,
  "description": [
    "The 510/Pod Attachment for EVRI connects to standard 510 cartridges and refillable e-juice pods. (Cartridge and pod pictured not included with attachment.) EVRI by Dip Devices is a multi-functional consumption solution. EVRI features a battery that connects magnetically to continuously evolving attachments. This item is for the 510/Pod Attachment only. The EVRI Battery and Vapor Tip Attachment can be purchased separately or with the EVRI Starter Pack. More attachments coming soon! EVRI evolves with consumption. 1% of all EVRI sales donated to drug policy reform via MPP.org and SSDP.org."
  ],
  "features": [
    "Compatible with Evri Vaporizer",
    "For Use with 510 Cartridges and Pods",
    "Easy Change Magnetic Connection",
    "Size: 4.625\" x 1\" x .875\""
  ]
}
