POST http://localhost:3004/api/products
Content-type: application/json

{
  "product_SKU":  "Apl-IPhnX-Slv",
  "product_name": "Apple",
  "product_model": "Apple iPhone X",
  "product_description": "We do more than hit the reset button. Before any device gets labeled Samsung Certified Pre-Owned, it gets completely taken apart and rebuilt by the same engineers who build our new phones. They replace worn out pieces, and we include the same one-year warranty our new phones come with for extra peace of mind.",
  "quantity_per_unit": 42,
  "unit_price": 36500,
  "discount_price": "",
  "product_color": "Silver",
  "product_image": "images/samsung-Apple-iphonex-silver",
  "network": {
    "technology": "GSM / HSPA / LTE"
  },
  "body": {
    "dimensions": "143.6 x 70.9 x 7.7 mm (5.65 x 2.79 x 0.30 in)",
    "weight": "174 g (6.14 oz)"
  },
  "display": {
    "displayType": "IPS LCD, 480 nits (peak)",
    "size": "6.0 inches, 109.8 cm2 (~82.7% screen-to-body ratio)",
    "resolution": "720 x 1640 pixels (~263 ppi density)"
  },
  "platform": {
    "os": "iOS 11.1.1, upgradable to iOS 14.2",
    "chipset": "Apple A11 Bionic (10 nm)"
  },
  "memory": {
    "internal": "64GB 3GB RAM, 256GB 3GB RAM NVMe"
  },
  "camera": {
    "main": "12MP+12MP",
    "selfie": "7MP"
  },
  "battery": {
    "batteryType": "Li-Ion 2716 mAh, non-removable (10.35 Wh)" 
  },
  "misc": {
    "colors": "Space Gray, Silver",
    "models": "A1865, A1901, A1902, A1903"
  }
}
