POST http://localhost:3004/api/products
Content-type: application/json

{
  "product_SKU":  "Tec-Pop4-SpPur",
  "product_name": "Tecno",
  "product_model": "Tecno POP 4",
  "product_description": "We do more than hit the reset button. Before any device gets labeled Samsung Certified Pre-Owned, it gets completely taken apart and rebuilt by the same engineers who build our new phones. They replace worn out pieces, and we include the same one-year warranty our new phones come with for extra peace of mind.",
  "quantity_per_unit": 42,
  "unit_price": 36500,
  "discount_price": "",
  "product_color": "Green",
  "product_image": "images/samsung-Tecno-pop4-green",
  "network": {
    "technology": "GSM / HSPA"
  },
  "body": {
    "dimensions": "144.0 x 73.8 x 10.6 mm",
    "weight": "183g"
  },
  "display": {
    "displayType": "IPS LCD, 480 nits (peak)",
    "size": "6.0 inches, 109.8 cm2 (~82.7% screen-to-body ratio)",
    "resolution": "720 x 1640 pixels (~263 ppi density)"
  },
  "platform": {
    "os": "Android 10, Go Edition",
    "chipset": "Mediatek Helio G80 (12 nm)"
  },
  "memory": {
    "internal": "128GB 6GB RAM"
  },
  "camera": {
    "main": "8MP",
    "selfie": "5MP"
  },
  "battery": {
    "batteryType": "Li-Po 5000 mAh, non-removable" 
  },
  "misc": {
    "colors": "Green, blue, cosmic radiance"
  }
}
