POST http://localhost:3004/api/smoke-products
Content-Type: application/json

{
  "name": "Mighty Portable Vaporizer by Storz & Bickel",
  "brand": "Storz & Bickel",
  "categories": "Vaporizer",
  "price": 133000,
  "description": [
    "The Mighty Vaporizer from Storz & Bickel delivers high quality vapor in a sleek, handheld design. The Mighty incorporates several cutting-edge thermal engineering features, enhancing the vaporization experience. The Mighty Vaporizer is a dual lithium-ion battery powered portable vaporizer that utilizes full convection hot air combined with conduction, and a high efficiency heat exchanger along with a LED temperature display and precise temperature control. About an inch taller and wider than Crafty, the Mighty vaporizer is almost twice the weight and features twice the battery capacity.",
    "The Mighty is hand-crafted in Germany by Storz & Bickel, the makers of the Volcano Vaporizer and Plenty Vaporizer, and is constructed of top quality materials for first-rate durability and functionality. The Mighty's vapor quality is similar to the Volcano: dense, aromatic, and pure. The Mighty's effective vapor production system makes for an enjoyable experience without the learning curve or multitude of components found in other vaporizers."
  ],
  "features": [
    "For Use with Dry Herbs",
    "For Use with Extracts and Liquids When Using included Liquid Pad",
    "Silent Two-Button Operation for Precise Temperature Control",
    "Full Convection Hot Air + Conduction Combined",
    "Haptic Vibration Alarm",
    "High Efficiency Heat Exchanger",
    "Battery & Temperature Displays"
  ]
}
