POST http://localhost:3004/api/smoke-products
Content-Type: application/json

{
  "name": "GRAV 16mm Octo-Taster w/ Silicone Skin",
  "brand": "Grav",
  "categories": "Pipe",
  "price": 4500,
  "description": [
    "This GRAV Octo-Taster is a perfect hybrid of silicone and glass. Enjoy the flavor of smoking with glass while having the unbreakable qualities of silicone. The silicone skin is bouncy and shock-absorbent to protect your glass taster. The pinched mouthpiece acts as an ash catcher and the silicone cap keeps your bud in place. The entire silicone skin comes off for easy cleaning, and you can just peel back the end cap during use. And instead of a normal restriction, the taster has a glass screen for an extra layer of filtration."
  ],
  "features": [
    "16mm Glass GRAV Taster",
    "Protective Silicone Skin",
    "Silicone Cover Holds Bud in Pla-ce",
    "Pinched Mouthpiece Ash Catcher",
    "Fits Perfectly in Your Pocket or Purse",
    "GRAV Decal",
    "Available in Several Colors",
    "Length: 4\"",
    "Glass Diameter: 16mm"
  ]
}
