POST http://localhost:3004/api/products/computers
Content-type: application/json

{
  "product_SKU": "HP-OMN-17t-JETBLK",
  "product_name": "HP",
  "product_model": "HP Omen 17t",
  "product_description": "",
  "quantity_per_unit": 24,
  "unit_price": 411000,
  "product_image": "images/hp-omen-17t-jet-black",
  "product_color": "Jet Black",
  "discount_price": "",
  "battery": "3-cell 37WHr 3.25 lithium-ion battery",
  "camera": "2-megapixel webcam; 8-megapixel rear camera",
  "display": "17.3\" diagonal FHD 144 Hz IPS anti-glare WLED-backlit (1920 x 1080)",
  "memory": "16 GB DDR4-2933 SDRAM (2 x 8 GB)",
  "processor": "Intel® Core™ i5-10300H (2.5 GHz, up to 4.5 GHz, 8 MB L3 cache, 4 cores)",
  "operating_system": "Windows 8.1 with Bing (64-bit)",
  "video_card": "NVIDIA® GeForce® GTX 1660 Ti (6 GB)",
  "hard_drive": "512 GB PCIe® NVMe™ TLC M.2 SSD + 1 TB PCIe® NVMe™ TLC M.2 SSD",
  "body": {
    "dimensions": "14.80 x 9.69 x 0.89 in",
    "weight": "4.6 lb"
  },
  "wireless": {
    "wifi": "802.11b/g/n (1x1) Wi-Fi® and Bluetooth® 4.2 combo",
    "bluetooth": "Bluetooth 4.2"
  },
  "misc": {
    "colors": "Jet Black, Natural Silver, Pale Gold, Scarlet Red, Lumiere Blue, Berry Mauve",
    "models": ""
  }
}
