PUT http://localhost:3004/api/products/computers/5fb82c654a162e30b452232c
Content-Type: application/json

{
  "product_SKU": "HP-PAV-GAM-16-SCTRED",
  "product_name": "HP",
  "product_model": "HP Pavilion Gaming Laptop - 16",
  "product_description": "",
  "quantity_per_unit": 26,
  "unit_price": 370000,
  "product_image": "images/hp-pavilion Gaming-16-scarlet-red",
  "product_color": "Scarlet Red",
  "discount_price": "",
  "battery": "3-cell, 52.5 Wh Li-ion",
  "camera": "2-megapixel webcam; 8-megapixel rear camera",
  "display": "40.9 cm (16.1\") diagonal FHD, 144 Hz, IPS, anti-glare, micro-edge, WLED-backlit, 300 nits, 72% NTSC (1920 x 1080)",
  "memory": "8 GB DDR4-2933 SDRAM (2 x 4 GB)",
  "processor": "Intel® Core™ i5-10300H (2.5 GHz base frequency, up to 4.5 GHz with Intel® Turbo Boost Technology, 8 MB L3 cache, 4 cores)",
  "operating_system": "Windows 10 Home 64",
  "video_card": "NVIDIA® GeForce® GTX 1650 (4 GB GDDR6 dedicated)",
  "hard_drive": "512 GB PCIe® NVMe™ M.2 SSD",
  "body": {
    "dimensions": "37 x 26.25 x 2.35 cm",
    "weight": "2.35 kg"
  },
  "wireless": {
    "wifi": "Realtek 802.11 b/g/n/ac (2x2) and Bluetooth® 5 combo",
    "bluetooth": "Bluetooth 5.0"
  },
  "misc": {
    "colors": "Jet Black, Natural Silver, Pale Gold, Scarlet Red, Lumiere Blue, Berry Mauve",
    "models": ""
  }
}
